### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'login')

### ISSUE THREAD

**Issue by aabouzaid** [bpmn-io/actions#27]
### Describe the Bug

When the action runs it shows this error:
```
Run bpmn-io/actions/weekly-notes@latest
  with:
    template-path: .github/ISSUE_TEMPLATE/WEEKLY_NOTE.md
    moderators-path: .github/workflows/moderators.json
    roles: moderator,summary-writer
    week-interval: 2
    token: ***
    community-worker: true
[weekly-notes] computing next issue title { currentWeek: { weekNumber: 27, year: 2024 }, weekInterval: 2 }
/home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:29256
  const lastIndex = findIndex(candidates, c => c.login === lastAssignee.login);
                                                                        ^

TypeError: Cannot read properties of null (reading 'login')
    at /home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:29256:73
    at /home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:31378:9
    at forEach (/home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:31440:16)
    at findIndex (/home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:31377:3)
    at getNextAssignee (/home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:29256:21)
    at /home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:32262:10
    at Array.map (<anonymous>)
    at run (/home/runner/work/_actions/bpmn-io/actions/latest/weekly-notes/index.js:32259:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.13.1
```

You can see it live here:
https://github.com/camunda/distribution/actions/runs/9809118739/job/27086303179#step:2:12

### Steps to Reproduce

Current workflow:

```
name: Weekly
on:
  issues:
    types: [closed]
jobs:
  createWeeklyIssue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - if: contains(github.event.issue.labels.*.name, 'weekly')
        name: Create new Issue
        uses: bpmn-io/actions/weekly-notes@latest
        with:
          template-path: ".github/ISSUE_TEMPLATE/WEEKLY_NOTE.md"
          moderators-path: ".github/workflows/moderators.json"
          roles: moderator,summary-writer
          week-interval: 2
```

### Expected Behavior

The action should run and create the weekly issue.

### Environment

- Host (Browser/Node version), if applicable: Node.js v20.13.1
- OS: Ubuntu 22.04.4 LTS
- Library version: latest (SHA:0f52595bff8ebf7ccb5e7eec2b882ead9f12c73b)
